// AUTOGENERATED FILE; see /tmp/abc/docker-dev/hack/make/.go-autogen
package dockerversion

var (
	GITCOMMIT string = "8ee89ed-dirty"
	VERSION   string = "1.9.1"
	BUILDTIME string = "Sun Feb 26 15:06:52 UTC 2017"

	IAMSTATIC string = "true"
	INITSHA1  string = ""
	INITPATH  string = ""
)
